services:
  - type: web
    name: licencia-autoclave
    env: python
    plan: starter
    region: oregon
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd src
      python server.py
    branch: main
