# render.yaml
services:
  - type: web
    name: licencia-autoclave           # Nombre del servicio en Render
    env: python                         # Entorno de ejecución
    plan: starter                       # Plan (puede ser free, starter, etc.)
    region: oregon                      # Región del datacenter (ajusta si quieres otra)
    autodeploy: true                    # Auto deploy desde tu rama principal
    buildCommand: |
      pip install -r requirements.txt
      python add_license.py            # Crea la licencia en licenses.db durante el build
    startCommand: python server.py      # Arranca tu FastAPI con uvicorn integrado
