# render.yaml
services:
  - type: web
    name: licencia-autoclave
    env: python
    plan: starter
    region: oregon
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      cd src
      python add_license.py
    startCommand: |
      cd src
      python server.py
    branch: main
